//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibClient.VelibServiceDocker {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int Available_bikesField;
        
        private int Bike_standsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Available_bikes {
            get {
                return this.Available_bikesField;
            }
            set {
                if ((this.Available_bikesField.Equals(value) != true)) {
                    this.Available_bikesField = value;
                    this.RaisePropertyChanged("Available_bikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Bike_stands {
            get {
                return this.Bike_standsField;
            }
            set {
                if ((this.Bike_standsField.Equals(value) != true)) {
                    this.Bike_standsField = value;
                    this.RaisePropertyChanged("Bike_stands");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Country_code {
            get {
                return this.Country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Country_codeField, value) != true)) {
                    this.Country_codeField = value;
                    this.RaisePropertyChanged("Country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServiceDocker.IVelibService")]
    public interface IVelibService {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément city de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStations", ReplyAction="*")]
        VelibClient.VelibServiceDocker.GetStationsResponse GetStations(VelibClient.VelibServiceDocker.GetStationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStations", ReplyAction="*")]
        System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetStationsResponse> GetStationsAsync(VelibClient.VelibServiceDocker.GetStationsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément city de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStation", ReplyAction="*")]
        VelibClient.VelibServiceDocker.GetStationResponse GetStation(VelibClient.VelibServiceDocker.GetStationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStation", ReplyAction="*")]
        System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetStationResponse> GetStationAsync(VelibClient.VelibServiceDocker.GetStationRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetContractsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetContracts", ReplyAction="*")]
        VelibClient.VelibServiceDocker.GetContractsResponse GetContracts(VelibClient.VelibServiceDocker.GetContractsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetContracts", ReplyAction="*")]
        System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetContractsResponse> GetContractsAsync(VelibClient.VelibServiceDocker.GetContractsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStations", Namespace="http://tempuri.org/", Order=0)]
        public VelibClient.VelibServiceDocker.GetStationsRequestBody Body;
        
        public GetStationsRequest() {
        }
        
        public GetStationsRequest(VelibClient.VelibServiceDocker.GetStationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetStationsRequestBody() {
        }
        
        public GetStationsRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public VelibClient.VelibServiceDocker.GetStationsResponseBody Body;
        
        public GetStationsResponse() {
        }
        
        public GetStationsResponse(VelibClient.VelibServiceDocker.GetStationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VelibClient.VelibServiceDocker.Station[] GetStationsResult;
        
        public GetStationsResponseBody() {
        }
        
        public GetStationsResponseBody(VelibClient.VelibServiceDocker.Station[] GetStationsResult) {
            this.GetStationsResult = GetStationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStation", Namespace="http://tempuri.org/", Order=0)]
        public VelibClient.VelibServiceDocker.GetStationRequestBody Body;
        
        public GetStationRequest() {
        }
        
        public GetStationRequest(VelibClient.VelibServiceDocker.GetStationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stationName;
        
        public GetStationRequestBody() {
        }
        
        public GetStationRequestBody(string city, string stationName) {
            this.city = city;
            this.stationName = stationName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStationResponse", Namespace="http://tempuri.org/", Order=0)]
        public VelibClient.VelibServiceDocker.GetStationResponseBody Body;
        
        public GetStationResponse() {
        }
        
        public GetStationResponse(VelibClient.VelibServiceDocker.GetStationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VelibClient.VelibServiceDocker.Station GetStationResult;
        
        public GetStationResponseBody() {
        }
        
        public GetStationResponseBody(VelibClient.VelibServiceDocker.Station GetStationResult) {
            this.GetStationResult = GetStationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContracts", Namespace="http://tempuri.org/", Order=0)]
        public VelibClient.VelibServiceDocker.GetContractsRequestBody Body;
        
        public GetContractsRequest() {
        }
        
        public GetContractsRequest(VelibClient.VelibServiceDocker.GetContractsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContractsRequestBody {
        
        public GetContractsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContractsResponse", Namespace="http://tempuri.org/", Order=0)]
        public VelibClient.VelibServiceDocker.GetContractsResponseBody Body;
        
        public GetContractsResponse() {
        }
        
        public GetContractsResponse(VelibClient.VelibServiceDocker.GetContractsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContractsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VelibClient.VelibServiceDocker.Contract[] GetContractsResult;
        
        public GetContractsResponseBody() {
        }
        
        public GetContractsResponseBody(VelibClient.VelibServiceDocker.Contract[] GetContractsResult) {
            this.GetContractsResult = GetContractsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : VelibClient.VelibServiceDocker.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.ClientBase<VelibClient.VelibServiceDocker.IVelibService>, VelibClient.VelibServiceDocker.IVelibService {
        
        public VelibServiceClient() {
        }
        
        public VelibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VelibClient.VelibServiceDocker.GetStationsResponse VelibClient.VelibServiceDocker.IVelibService.GetStations(VelibClient.VelibServiceDocker.GetStationsRequest request) {
            return base.Channel.GetStations(request);
        }
        
        public VelibClient.VelibServiceDocker.Station[] GetStations(string city) {
            VelibClient.VelibServiceDocker.GetStationsRequest inValue = new VelibClient.VelibServiceDocker.GetStationsRequest();
            inValue.Body = new VelibClient.VelibServiceDocker.GetStationsRequestBody();
            inValue.Body.city = city;
            VelibClient.VelibServiceDocker.GetStationsResponse retVal = ((VelibClient.VelibServiceDocker.IVelibService)(this)).GetStations(inValue);
            return retVal.Body.GetStationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetStationsResponse> VelibClient.VelibServiceDocker.IVelibService.GetStationsAsync(VelibClient.VelibServiceDocker.GetStationsRequest request) {
            return base.Channel.GetStationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetStationsResponse> GetStationsAsync(string city) {
            VelibClient.VelibServiceDocker.GetStationsRequest inValue = new VelibClient.VelibServiceDocker.GetStationsRequest();
            inValue.Body = new VelibClient.VelibServiceDocker.GetStationsRequestBody();
            inValue.Body.city = city;
            return ((VelibClient.VelibServiceDocker.IVelibService)(this)).GetStationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VelibClient.VelibServiceDocker.GetStationResponse VelibClient.VelibServiceDocker.IVelibService.GetStation(VelibClient.VelibServiceDocker.GetStationRequest request) {
            return base.Channel.GetStation(request);
        }
        
        public VelibClient.VelibServiceDocker.Station GetStation(string city, string stationName) {
            VelibClient.VelibServiceDocker.GetStationRequest inValue = new VelibClient.VelibServiceDocker.GetStationRequest();
            inValue.Body = new VelibClient.VelibServiceDocker.GetStationRequestBody();
            inValue.Body.city = city;
            inValue.Body.stationName = stationName;
            VelibClient.VelibServiceDocker.GetStationResponse retVal = ((VelibClient.VelibServiceDocker.IVelibService)(this)).GetStation(inValue);
            return retVal.Body.GetStationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetStationResponse> VelibClient.VelibServiceDocker.IVelibService.GetStationAsync(VelibClient.VelibServiceDocker.GetStationRequest request) {
            return base.Channel.GetStationAsync(request);
        }
        
        public System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetStationResponse> GetStationAsync(string city, string stationName) {
            VelibClient.VelibServiceDocker.GetStationRequest inValue = new VelibClient.VelibServiceDocker.GetStationRequest();
            inValue.Body = new VelibClient.VelibServiceDocker.GetStationRequestBody();
            inValue.Body.city = city;
            inValue.Body.stationName = stationName;
            return ((VelibClient.VelibServiceDocker.IVelibService)(this)).GetStationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VelibClient.VelibServiceDocker.GetContractsResponse VelibClient.VelibServiceDocker.IVelibService.GetContracts(VelibClient.VelibServiceDocker.GetContractsRequest request) {
            return base.Channel.GetContracts(request);
        }
        
        public VelibClient.VelibServiceDocker.Contract[] GetContracts() {
            VelibClient.VelibServiceDocker.GetContractsRequest inValue = new VelibClient.VelibServiceDocker.GetContractsRequest();
            inValue.Body = new VelibClient.VelibServiceDocker.GetContractsRequestBody();
            VelibClient.VelibServiceDocker.GetContractsResponse retVal = ((VelibClient.VelibServiceDocker.IVelibService)(this)).GetContracts(inValue);
            return retVal.Body.GetContractsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetContractsResponse> VelibClient.VelibServiceDocker.IVelibService.GetContractsAsync(VelibClient.VelibServiceDocker.GetContractsRequest request) {
            return base.Channel.GetContractsAsync(request);
        }
        
        public System.Threading.Tasks.Task<VelibClient.VelibServiceDocker.GetContractsResponse> GetContractsAsync() {
            VelibClient.VelibServiceDocker.GetContractsRequest inValue = new VelibClient.VelibServiceDocker.GetContractsRequest();
            inValue.Body = new VelibClient.VelibServiceDocker.GetContractsRequestBody();
            return ((VelibClient.VelibServiceDocker.IVelibService)(this)).GetContractsAsync(inValue);
        }
    }
}
